# Development overrides for docker-compose
version: '3.8'

services:
  backend:
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: npm run dev

  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      NODE_ENV: development
    command: npm run dev

  database:
    ports:
      - "5432:5432"  # Expose database port for development tools

  redis:
    ports:
      - "6379:6379"  # Expose Redis port for development tools